AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamdize
  
  Sample SAM Template for lamdize

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  UrlShortener:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: UrlShortener/
      Handler: UrlShortener
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          # this variable decides whether to run the app as a lambda function or not 
          Lambda : "True"
          #dynamo table name
          TableName :
          #index names 
          LongUrlIndexName : 
          ShortUrlIndexName : 
          #public key for jwt token validation for cognito 
          #it usually has format like https://cognito-idp.{REGION}.amazonaws.com/{REGION}_dLWA8fRYj/.well-known/jwks.json
          PublicKeysURL :
          #region of database 
          Region : 
          #cognito client id 
          ClientId : 
          BaseUrl : http://localhost:8080/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"


