version: "3.8"
services:
  dynamodb-local:
    restart: always
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:1.11.119"
    container_name: dynamodb-local-sabbir
    ports:
      - "8000:8000"
    volumes:
      - "./:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
